---
title: "TutoR"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This webpage contains tutorials on using the R statistical programming language.
The tutorials are organized into basic, intermediate and advanced. 
If you are new to R you should start with the basics. 
Some of the tutorials will have code files and data associated with them which you can find on the guthub site under `projects`.
Note that this page is a work in progress. 
The tutorials below that are blue are active, while those that are black are in the works to be developed.

[Link to github page](https://github.com/auqmer/TutoR)

## Tutorials

### Basic

* Introduction to R
* Introduction to RStudio
* Elements of Programming
* Basic Object Types
* Assignment and Environments
* Functions
* Complex Objects
* File, Folders, Paths, and Projects

### Intermediate

* Using R Markdown
* [Using `ggplot2`](https://auqmer.github.io/TutoR/ggplot2_tutorial.html)
* Reshaping Data with `tidyr`
* Using `data.table`
* Reshaping Data with `data.table`
* Using `git` and GitHub for Version Control

### Advanced


